Added Parkinson's law
icyflame/awesome-social-science pull request #29
Opened 2017-12-05 13:42 UTC by priyankark

Felt it deserved to be on the list. Contributing as a part of KWOC.

2017-12-05 14:41 UTC, Megha66 commented
Relateable!!!

2017-12-07 07:12 UTC, icyflame requested changes

2017-12-07 07:12 UTC, icyflame commented on readme.md
> +This adage explains why you end up studying the majority of your syllabus one day before the exam despite the fact that you probably had over a week to study.
Paragraph should be longer

2017-12-07 07:12 UTC, icyflame commented on readme.md
> +> Parkinson's law is the adage that "work expands so as to fill the time available for its completion". It is also sometimes applied to the growth of the bureaucratic apparatus in an organization.
This should be shorter. Preferably only one small sentence that captures the essence of the entry

2017-12-07 07:12 UTC, icyflame commented on readme.md
> +[R: A Beginners Guide To Parkinson’s Law: How To Do More Stuff By Giving Yourself Less Time](https://impossiblehq.com/parkinsons-law/)
Add atleast one more reference

2017-12-07 07:52 UTC, priyankark commented
Made suggested changes. Please review.

2017-12-07 13:56 UTC, icyflame requested changes

2017-12-07 13:56 UTC, icyflame commented on readme.md
> +This adage explains why you end up studying the majority of your syllabus one day before the exam despite the fact that you probably had over a week to study. Interestingly, it is used to explain the
wrap at 70 characters

2017-12-07 13:56 UTC, icyflame commented on readme.md
> +[R: What is Parkinson's law: The Hindu](http://www.thehindu.com/opinion/op-ed/what-is-parkinsons-law-in-management/article19758089.ece)
this reference is unsatisfactory (too short). please find another better reference.

2017-12-07 15:20 UTC, priyankark commented
Made changes. Please review.

2017-12-08 15:02 UTC, icyflame requested changes
References are solid. Changes are almost done. Some final problems to be fixed. Thanks for your enthusiasm! :smile:

2017-12-08 15:02 UTC, icyflame commented on readme.md
> +### [Parkinson's law](https://en.wikipedia.org/wiki/Parkinson%27s_law)
Four pound signs.

2017-12-08 15:02 UTC, icyflame commented on readme.md
> +> Parkinson's law is the adage that "work expands so as to fill the time available for its completion".
No need to put the introductory text, just mention the adage (without double quotes). See other adages for ref

2017-12-08 15:02 UTC, icyflame commented on readme.md
> +despite the fact that you probably had over a week to study.Interestingly, it is used to
Whitespace after periods

2017-12-08 16:04 UTC, priyankark commented
Thank you for your patience and love the idea for this list!

2017-12-11 03:58 UTC, priyankark commented on readme.md
> +### [Parkinson's law](https://en.wikipedia.org/wiki/Parkinson%27s_law)
Changes made

2017-12-11 06:56 UTC, icyflame approved these changes

2017-12-11 06:56 UTC, merged