Added Multiple Personality Disorder
icyflame/awesome-social-science pull request #31
Opened 2017-12-07 09:10 UTC by Budcoderr

2017-12-08 14:42 UTC, icyflame reviewed
- fix grammar in the paragraph
- reduce the length of oneliner about MPD

2017-12-08 14:43 UTC, icyflame requested changes
- fix grammar in the paragraph
- reduce the length of oneliner about MPD

2017-12-13 10:13 UTC, Budcoderr commented
Changes done. Please review

2017-12-14 14:22 UTC, icyflame requested changes
Please proof read entries before submitting

2017-12-14 14:22 UTC, icyflame commented on readme.md
> +>Condition in which distinct identities alternately take control of—an individual
space

2017-12-14 14:22 UTC, icyflame commented on readme.md
> +In 1791, the first detailed account of "exchanged personality" was written about a 20-year-old German woman. DID was majorly studied between 1880 and 1920 and in 1944. According to Mosby's Medical Di
What is DID? This whole paragraph lacks context

2017-12-25 04:05 UTC, icyflame commented
Closing this for now. Please re-open after making the request changes.

2017-12-25 04:05 UTC, closed without merging