Added Fregoli Delusion
icyflame/awesome-social-science pull request #35
Opened 2017-12-08 11:23 UTC by d3vil0p3r

I've made the following changes to `readme.md` file:
- Fixed trailing whitespaces.
- Added **Fregoli Delusion** to the *Psychological Syndromes* section.
- Updated the table of contents.

@icyflame kindly review.

2017-12-08 13:20 UTC, Megha66 commented
fregoli delusion is interesting. nice entry.

2017-12-08 13:25 UTC, d3vil0p3r commented
Thanks @Megha66. Indeed it is **one of the many** interesting syndromes out there!

2017-12-08 15:14 UTC, icyflame requested changes

2017-12-08 15:14 UTC, icyflame commented on readme.md
> +Its a rare disorder in which a person holds a delusional belief that different
apostrophe

2017-12-08 15:14 UTC, icyflame commented on readme.md
> +[R: Fregoli Delusion](https://www.ncbi.nlm.nih.gov/pubmed/25219764)
This is a paper, that isn't ideal. Please find two other references.

2017-12-08 15:55 UTC, d3vil0p3r commented
@icyflame done! kindly review.

2017-12-09 07:22 UTC, icyflame approved these changes

2017-12-09 07:25 UTC, closed without merging