UpdateAttention deficit hyperactivity disorder
icyflame/awesome-social-science pull request #62
Opened 2017-12-18 14:30 UTC by HariMahi

2017-12-20 05:24 UTC, icyflame requested changes

2017-12-20 05:24 UTC, icyflame commented on readme.md
> +  - [Attention deficit hyperactivity disorder](#attention-deficit-hyperactivity-disorder)
d, h and d should be in uppercase. Fix the hyperlink (see the example of DKE and check this before submitting for review)

2017-12-20 05:24 UTC, icyflame commented on readme.md
> +#### [Attention deficit hyperactivity disorder](https://en.wikipedia.org/wiki/Attention_deficit_hyperactivity_disorder) [ADHD]
d, h and d in uppercase

2017-12-20 05:24 UTC, icyflame commented on readme.md
> +neurodevelopmental type. It is characterized by problems paying attention,
problems _in_ paying attention

2017-12-25 04:07 UTC, icyflame requested changes

2017-12-25 04:07 UTC, icyflame commented on readme.md
> +  - [Attention Deficit Hyperactivity Disorder](#attention-deficit-hyperactivity-disorder)
This hyperlink is still incorrect

2017-12-25 04:42 UTC, HariMahi commented
#### [Attention Deficit Hyperactivity Disorder](https://en.wikipedia.org/wiki/Attention_deficit_hyperactivity_disorder)  [ADHD]
 
I have made the changes as you said already.

2017-12-25 05:01 UTC, HariMahi commented
I have updated the hyperlink

2017-12-25 16:45 UTC, icyflame requested changes

2017-12-25 16:45 UTC, icyflame commented on readme.md
> +[R: medlineplus.gov](https://medlineplus.gov/attentiondeficithyperactivitydisorder.html)
Ref too short.

2017-12-30 03:29 UTC, closed without merging