Add Kleptomania
icyflame/awesome-social-science pull request #68
Opened 2017-12-21 01:28 UTC by HariMahi

2017-12-25 17:06 UTC, icyflame requested changes

2017-12-25 17:06 UTC, icyflame commented on readme.md
> +Kleptomania or klopemania is the inability to refrain from the urge
Fix grammar. Paragraph should be longer

2017-12-25 17:06 UTC, icyflame commented on readme.md
> +[R: minddisorders.com](http://www.minddisorders.com/Kau-Nu/Kleptomania.html)
Please add one more ref. minddisorders.com is rather short.

2017-12-28 01:03 UTC, HariMahi commented
Review the PRs

On Mon, Dec 25, 2017 at 10:36 PM, Siddharth Kannan <notifications@github.com
> wrote:

> *@icyflame* requested changes on this pull request.
> ------------------------------
>
> In readme.md
> <https://github.com/icyflame/awesome-social-science/pull/68#discussion_r158651091>
> :
>
> > @@ -431,6 +432,20 @@ context. There have been no treatment methods discovered as of now.
>
>  [R: National Institute of Neurological Disorders and Stroke](https://www.ninds.nih.gov/Disorders/All-Disorders/Prosopagnosia-Information-Page)
>
> +#### [Kleptomania](https://en.wikipedia.org/wiki/Kleptomania)
> +
> +> An impulse control disorder that results in an irresistible urge to steal
> +
> +Kleptomania or klopemania is the inability to refrain from the urge
>
> Fix grammar. Paragraph should be longer
> ------------------------------
>
> In readme.md
> <https://github.com/icyflame/awesome-social-science/pull/68#discussion_r158651098>
> :
>
> > @@ -431,6 +432,20 @@ context. There have been no treatment methods discovered as of now.
>
>  [R: National Institute of Neurological Disorders and Stroke](https://www.ninds.nih.gov/Disorders/All-Disorders/Prosopagnosia-Information-Page)
>
> +#### [Kleptomania](https://en.wikipedia.org/wiki/Kleptomania)
> +
> +> An impulse control disorder that results in an irresistible urge to steal
> +
> +Kleptomania or klopemania is the inability to refrain from the urge
> +for stealing items and is usually done for reasons other than personal
> +use or financial gain. First described in 1816, kleptomania is classified
> +in psychiatry as an impulse control disorder.
> +
> +[R: PsychologyToday](https://www.psychologytoday.com/conditions/kleptomania)
> +
> +[R: minddisorders.com](http://www.minddisorders.com/Kau-Nu/Kleptomania.html)
>
> Please add one more ref. minddisorders.com is rather short.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/icyflame/awesome-social-science/pull/68#pullrequestreview-85493161>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AcGMgT8wZx_sIgY9yyy6K3050P7HbXE8ks5tD9X7gaJpZM4RJPDQ>
> .
>

2018-03-20 14:01 UTC, icyflame commented
This needs more work. The current paragraph is not satisfactory.

2018-03-20 14:01 UTC, closed without merging